#ifndef ALGORITHMS_AND_DATA_STRUCTS_MY_HYPER_LOG_LOG_HPP
#define ALGORITHMS_AND_DATA_STRUCTS_MY_HYPER_LOG_LOG_HPP

class HyperLogLog{
public:
private:
};

#endif //ALGORITHMS_AND_DATA_STRUCTS_MY_HYPER_LOG_LOG_HPP
